%macro cdr(r,ds,vds,lib);
* Close up to 10 opened tables *;
dm 'next VIEWTABLE; end; next VIEWTABLE; end; next VIEWTABLE; end; next VIEWTABLE; end; next VIEWTABLE; end; next VIEWTABLE; end; next VIEWTABLE; end; next VIEWTABLE; end; next VIEWTABLE; end; next VIEWTABLE; end;';
%if %length(&vds)=0 %then %let vds=v_&ds;
%if %length(&lib)=0 %then %let lib=sds;
%let OPT=;
data TMP1; length SRC $5 CNT 8 DIFVARS $1000; SRC="MAIN"; call missing(of CNT DIFVARS); set &lib..&DS(&opt.); if _N_=&R; run;
data TMP2; SRC="VAL"; set &VDS(&opt.); if _N_=&R; run;
data TMP3(drop=I);
  set TMP1 TMP2;
  array C(*) _character_; array N(*) _numeric_;
  if _N_=2 then SRC="DIFF";
  do i=1 to hbound(C);
    if C{i} ne lag(C{i}) and vname(C{i}) not in ("SRC" "DIFVARS") then do; if _N_ ne 1 then C{i}="/\"; CNT+1; DIFVARS=catx(", ",DIFVARS,vname(C{i})); end;
    else if vname(C{i}) not in ("SRC" "CNT" "DIFVARS" "I") then call missing(C{i});
  end;
  do i=1 to hbound(N);
    if N{i} ne lag(N{i}) and vname(N{i}) not in ("CNT" "I") then do;       if _N_ ne 1 then N{i}=1;    CNT+1; DIFVARS=catx(", ",DIFVARS,vname(N{i})); end;
    else if vname(N{i}) not in ("CNT" "I") then call missing(N{i});
  end;
  if _N_=1 then CNT=.; else output;
run;
data TMP3; set TMP1 TMP3 TMP3 TMP3 TMP2; run;
proc sql; drop table TMP1, TMP2; quit;
%put %str(ALE)RT_I: Please open table work.TMP3 with comparison results.;
dm "viewtable work.TMP3 colhead=names";
%mend;

* R=number of record to compare, DS=name of prod dataset, VDS=name of val dataset, LIB=library for prod side dataset *;
%cdr(13, EG);
