*** Macro to get list of files in specified folder ***;
%macro files(dir=,ext=,out=);
  *** dir: folder path, ext - list of extensions to be kept, out - output dataset name ***;
  %if %length(&dir)=0 %then %do;
    %let rc = %sysfunc(filename(fr,.));
    %let dir = %sysfunc(pathname(&fr));
    %let rc = %sysfunc(filename(fr));
    %put NOTE: DIR not specified, use current folder:;
    %put NOTE: DIR=%left(&dir);
  %end;
  %if %length(&out)=0 %then %do;
    %put NOTE: OUT not specified, set to FILES;
    %let out=FILES;
  %end;
  %if not %index(&ext,%str(%')) and not %index(&ext,%str(%")) %then %do;
    %let ext=%sysfunc(tranwrd( %sysfunc(compbl(%upcase("%left(&ext)"))), %str( ), %str(" ") ));
    %put NOTE: &=ext;
  %end;
  * Get list of files in the folder *;
  data &out.(drop=FREF ID I);
    length FREF $8 PATH $256 NAME EXT $200;
    PATH=strip("&dir");
    ID = filename(FREF,"&dir.");
    ID = dopen(FREF);
    do i = 1 to dnum(ID);
      NAME = strip(dread(ID,i));
      if index(reverse(strip(NAME)),".") then EXT=upcase(substr(NAME,length(NAME)-index(reverse(strip(NAME)),".")+2));
      else EXT=" ";
      output;
    end;
    ID = dclose(ID);
    ID = filename(FREF);
  run;
  %if %length(&ext)>2 %then %do;
    data &out.;
      set &out.;
      if EXT not in (&ext.) then delete;
    run;
  %end;
%mend;

