************************************************************;
*  Program name     : v_m_tlf.sas
*  Project          : NA
*  Written by       : Anton Kamyshev 
*  Date of creation : 20250905
*  Description      : To validate tables
*  Input file       :
*  Output file      : v_xxx.sas7bdat
*  Revision History :
*  Date      Author   Description of the change
**********************************************************************************;
***** Tis file should be included at the very beginning of the validation TLF program --> %include "v_m_tlf.sas";

***** Include setup and study-specific validation macros, clean working area;
dm 'log;clear;';
%include "call setup.sas";
proc delete data = work._all_; run;

* List of treatments to use in validation datasets (should be subset of preload format TRTN) *;
%let _default_trt_seq = 1 2 3 4 99;

* Preload format for "treatment" columns - should include all possible treatments, treatment columns in datasets can be limited by macro var _DEFAULT_TRT_SEQ *;
proc format;
  value trtn 0=0 1=1 2=2 3=3 4=4 5=5 6=6 7=7 8=8 9=9 77=77 88=88 99=99;
run;

/*** VALIDATION TLF MACRO CALLS - detailed description of parameters see above in macro defibnitions ***
 *** IMPORTANT: Treatment variable passed in TRT parameters should be numeric with preload format TRTN applied (1 = 1, 2 = 2, etc) to create columns even if treatment is not in the subset 
 ***            Categorical variables can have preload format applied - in this case categories will be created even if missed in the data

%row(inds,where,outds,by,trt,var,lbl,sec=1,ord=1,dropds=Y,stat=N,prefn=TRT_N_,prefe=TRT_E_);      * Macro to calculate one-row counts *;
%cat(inds,where,outds,by,trt,cat,lbl,highlow=,sec=1,dropds=Y,stat=N,prefn=TRT_N_,prefe=TRT_E_);   * Macro to get categorical counts *;
%nst(inds,where,outds,by,trt,cat,scat,highlow=,sec=1,dropds=Y,stat=N,prefn=TRT_N_,prefe=TRT_E_);  * Macro to create nested counts (multiple categories with subcategories) *;

%bign(inds,where,by,trt,outds,dropds=Y);                                                          * Macro to get BigN counts for NPCNT macro *;
%npcnt(inds, outds, bign, by, pcntwhere=1, type=1, pct=N, miss2zero=Y, zerowhere=1, dropds=Y);    * Macro to calculate percentage and create "nn (pp.p%)" values for ROW and CAT results *;

%get_prec(inds,where,var,outds,outmvar);                                                          * Get maximal number of DP for specified subset, can be used in STC *;
%stc(inds,where,outds,by,trt,var,lbl,highlow=,sec=1,dropds=Y,statlst=,ci95lev=2,prchg=0,prset=);  * Macro to get N MEAN SD MEANSD MEDIAN Q1 Q3 Q1Q3 IQR MIN MAX MINMAX CI95 counts *;

%lbl(outds,lbl,sec=1,ord=0,dropds=Y,prefn=TRT_N_,trtlist=&_default_trt_seq);  * Add blank row with label *;
%bylbl(inds=,outds=,by=,pref=N_PCNT_,ord=-1);                                 * Add new rows with labels for by-groups*;
%ord(inds=, outds=, where=, neword=, keepord=0, keepsec=13011982, dropds=Y);  * Reorder rows within sections *;

%prepval(inds, outds, vars, suppress);  * Convert validation dataset (variables N_PCNT_xx) to be ready for comparison with main dataset (variables COLx) *;
%compval(id);                           * Compare main and validation datasets *;

***/

* Macro to calculate one-row counts *;
%macro row(inds,where,outds,by,trt,var,lbl,sec=1,ord=1,dropds=Y,stat=N,prefn=TRT_N_,prefe=TRT_E_);
  * by - by-variables, trt - treatment variable, var - variable to be used to count records, lbl - label for the row, stat=NE for patients (N) and events (E) *;
  %if %length(&trt)=0 %then %put %str(WAR)NING: Parameter TRT is blank, please pass the value (numeric variable).;
  %if %length(&var)=0 %then %let var=USUBJID;
  %if %length(&outds)=0 %then %let outds=SEC_&sec._ROW_&ord.;
  %let sql_by = %upcase(%sysfunc(tranwrd(%sysfunc(compbl(%str(&by))),%str( ),%str(,))));
  %if not %index(%nrbquote(&lbl),%str(%")) %then %let lbl="&lbl";
  %local trtfmt catfmt;
  proc sql noprint;
    select FORMAT into :trtfmt trimmed from sashelp.VCOLUMN where LIBNAME='WORK' and upcase(MEMNAME)=upcase("&inds") and upcase(NAME)=upcase("&trt");
  quit;
  %put NOTE: &=trtfmt;
  proc sort data=&inds.%if %length(&where)>0 %then %do;(where=(&where.))%end; out=&inds._R1; by &by. &trt. USUBJID; run;
  data &inds._R1;
    set &inds._R1;
    by &by. &trt. USUBJID;
    if first.USUBJID then _COUNTERN=1; else _COUNTERN=.; * Count patients *; 
    _COUNTERE=1; * Count events *; 
    length LABEL $200;
    LABEL=&lbl.;
  run;
  * Workaround for case when there are no records per current condition *;
  %let R1CNT=0;
  proc sql noprint;
    select distinct &trt. into :TRTLST separated by " " from &inds. order by &trt.;
    select count(*) into :R1CNT trimmed from &inds._R1;
  quit;
  %put NOTE: &=r1cnt &=trtlst;
  %if &r1cnt=0 %then %do;
    data &inds._R1;
      set &inds.;
      if _N_=1;
      call missing(of _all_);
      _COUNTERN=.;
      _COUNTERE=.;
      length LABEL $200;
      LABEL=&lbl.;
      %do _i=1 %to %sysfunc(countw(&trtlst.));
        &trt. = %scan(&trtlst.,&_i.);
        output;
      %end;
    run;
  %end;
  * ^^^ *;

  * Check preload formats for by-variables *;
  %local trtfmt by_formatted by_formats by_renamed by_created by_orig by_sort;
  %if %length(&by.)>0 %then %do _i=1 %to %sysfunc(countw(&by.));
    %let byfmt&_i=;
    proc sql noprint;
      select FORMAT into :byfmt&_i trimmed from sashelp.VCOLUMN where LIBNAME='WORK' and upcase(MEMNAME)=upcase("&inds") and upcase(NAME)=upcase("%scan(&by,&_i)");
      %if %length(&&byfmt&_i)>0 %then %do;
        %put NOTE: Preload format identified for BY-variable %scan(&by,&_i): &&byfmt&_i;
        %let by_formatted = %left(&by_formatted) %scan(&by,&_i);
        %let by_formats   = %left(&by_formats) %left(&&byfmt&_i);
        %let by_renamed   = %left(&by_renamed) %scan(&by,&_i)=%scan(&by,&_i)_ORIG;
        %let by_created   = %left(&by_created) %scan(&by,&_i)=put(%scan(&by,&_i)_ORIG,%left(&&byfmt&_i))%str(;);
        %let by_orig      = %left(&by_orig) %scan(&by,&_i)_ORIG;
        %let by_sort      = %left(&by_sort) %scan(&by,&_i)_ORIG;
      %end;
      %else %let by_sort  = %left(&by_sort) %scan(&by,&_i); * To sort by-categories by unformatted values *;
    quit;
  %end;
  %let by_created=%sysfunc(tranwrd(&by_created,%str( ),%str(; )));
  %put NOTE: &=by_formatted; * AVISITN *;
  %put NOTE: &=by_formats;   * vis.    *;
  %put NOTE: &=by_renamed;   * AVISITN=AVISITN_ORIG *;
  %put NOTE: &=by_created;   * AVISITN=put(AVISITN_ORIG,vis.); *;
  %put NOTE: &=by_orig;      * AVISITN_ORIG *;

  * Process by-variables with preload format to keep _orig variables for sorting purpose *;
  %if %length(&by_formatted.)>0 %then %do;
    data &inds._R1;
      set &inds._R1;
      %do i=_1 %to %sysfunc(countw(&by_formatted.));
        %scan(&by_orig.,&_i.) = %scan(&by_formatted.,&_i.); * Create copy of the original variable *;
      %end;
    run;
  %end;

  proc summary data=&inds._R1 nway completetypes missing;
    class LABEL;
    %if %length(&by)>0 %then %do _i=1 %to %sysfunc(countw(&by.)); class %scan(&by,&_i) %if %length(&&byfmt&_i)>0 %then / preloadfmt mlf;; %end; * Cycle through BYVARs *;
    class &trt. %if %length(&trtfmt.)>0 %then / preloadfmt mlf;; * TRTVAR *;
    var _COUNTERN;
    output out=&inds._R1N(drop=_type_ _freq_) n=N;
  run;
  proc summary data=&inds._R1 nway completetypes missing;
    class LABEL;
    %if %length(&by)>0 %then %do _i=1 %to %sysfunc(countw(&by.)); class %scan(&by,&_i) %if %length(&&byfmt&_i)>0 %then / preloadfmt mlf;; %end; * Cycle through BYVARs *;
    class &trt. %if %length(&trtfmt.)>0 %then / preloadfmt mlf;; * TRTVAR *;
    var _COUNTERE;
    output out=&inds._R1E(drop=_type_ _freq_) n=E;
  run;
  %if &r1cnt=0 %then %do;
  proc sql;
    update &inds._R1N set N=0;
    update &inds._R1E set E=0;
  quit;
  %end;
  proc transpose data=&inds._R1N(where=(input(&trt.,?best.) in (&_default_trt_seq.))) out=&inds._R1NT(drop=_:) prefix=&prefn.;
    by &by. LABEL;
    id &trt.;
    var N;
  run;
  proc transpose data=&inds._R1E(where=(input(&trt.,?best.) in (&_default_trt_seq.))) out=&inds._R1ET(drop=_:) prefix=&prefe.;
    by &by. LABEL;
    id &trt.;
    var E;
  run;
  data &outds.;
    merge &inds._R1NT &inds._R1ET;
    by &by. LABEL;
    SEC = &sec.;
    ORD = &ord.;
    %if not %index(%upcase(&stat),N) %then drop &prefn.:;;
    %if not %index(%upcase(&stat),E) %then drop &prefe.:;;
  run;
  * Add unformatted by-variables for sorting purpose *;
  %if %length(&by_formatted.)>0 %then %do _i=1 %to %sysfunc(countw(&by_formatted.));
    %put NOTE: Add unformatted BY-variable %scan(&by_orig.,&_i.,)[%scan(&by_formats.,&_i.,)] for sorting purposes.;
    proc format cntlout=_FMT_(where=( strip(upcase(FMTNAME))||"."="%scan(&by_formats.,&_i.,)" ) keep=FMTNAME START LABEL); run;
    data _FMT_; set _FMT_; %scan(&by_orig.,&_i.,) = input(START,%scan(&by_formats.,&_i.,)); rename LABEL=%scan(&by_formatted.,&_i.,); run;
    proc sql;
      create table _TMP_ as select a.*, b.%scan(&by_orig.,&_i.,)
        from &outds. as a left join _FMT_ as b on a.%scan(&by_formatted.,&_i.,)=b.%scan(&by_formatted.,&_i.,);
    quit;
    data &outds.; set _TMP_; run;
    proc sql noprint; drop table _TMP_, _FMT_; quit;
  %end;  
  %if %upcase(&dropds)=Y %then %do; proc sql; drop table &inds._R1, &inds._R1N, &inds._R1E, &inds._R1NT, &inds._R1ET; quit; %end;
%mend row;

* Macro to get categorical counts *;
%macro cat(inds,where,outds,by,trt,cat,lbl,highlow=,sec=1,dropds=Y,stat=N,prefn=TRT_N_,prefe=TRT_E_);
  * by - additional by-variables, cat - categorical variable, lbl - variable for first (summary) row, highlow - H\L to count patient only once in highest or lowest category, stat=NE where N is for patients and E for EVENTS *;
  %if %length(&trt)=0 %then %put %str(WAR)NING: Parameter TRT is blank, please pass the value (numeric variable).;
  %if %length(&cat)=0 %then %put %str(WAR)NING: Parameter CAT is blank, please pass the name of the categorical variable.;
  %if %length(&sec)=0 %then %let sec=1;
  %if %length(&outds)=0 %then %let outds=SEC_&sec._CAT;
  %let sql_by = %upcase(%sysfunc(tranwrd(%sysfunc(compbl(%str(&by))),%str( ),%str(,))));
  %if not %index(%nrbquote(&lbl),%str(%")) %then %let lbl="&lbl";
  proc sort data=&inds.%if %length(&where)>0 %then %do;(where=(&where.))%end; out=&inds._C1(where=(cmiss(&trt.,&cat.)=0)); by &by. &trt. USUBJID &cat.; run;
  data &inds._C1;
    set &inds._C1;
    by &by. &trt. USUBJID &cat.;
    _COUNTERN=1; * Count patients in all categories initially *;
    %if %upcase(&highlow)=H %then if not last.USUBJID  then _COUNTERN=.;; * if H then count only in highest category;
    %if %upcase(&highlow)=L %then if not first.USUBJID then _COUNTERN=.;; * if L then count only in lowest category;
    %if %length(&highlow)=0 %then if not first.&cat. then _COUNTERN=.;; * If HIGHLOW is blank, then count once per category *;
    _COUNTERE=1; * Count events *;
  run;
  * Workaround for case when there are no records per current condition *;
  %let C1CNT=0;
  proc sql noprint;
    select distinct &trt. into :TRTLST separated by " " from &inds. order by &trt.;
    select count(*) into :C1CNT trimmed from &inds._C1;
  quit;
  %put NOTE: &=c1cnt &=trtlst;
  %if &c1cnt=0 %then %do;
    data &inds._C1;
      set &inds.;
      if _N_=1;
      call missing(of _all_);
      _COUNTERN=.;
      _COUNTERE=.;
      %do _i=1 %to %sysfunc(countw(&trtlst.));
        &trt. = %scan(&trtlst.,&_i.);
        output;
      %end;
    run;
  %end;
  * ^^^ *;

  * Check preload formats for by-variables *;
  %local by_formatted by_formats by_renamed by_created by_orig by_sort;
  %if %length(&by.)>0 %then %do _i=1 %to %sysfunc(countw(&by.));
    %let byfmt&_i=;
    proc sql noprint;
      select FORMAT into :byfmt&_i trimmed from sashelp.VCOLUMN where LIBNAME='WORK' and upcase(MEMNAME)=upcase("&inds") and upcase(NAME)=upcase("%scan(&by,&_i)");
      %if %length(&&byfmt&_i)>0 %then %do;
        %put NOTE: Preload format identified for BY-variable %scan(&by,&_i): &&byfmt&_i;
        %let by_formatted = %left(&by_formatted) %scan(&by,&_i);
        %let by_formats   = %left(&by_formats) %left(&&byfmt&_i);
        %let by_renamed   = %left(&by_renamed) %scan(&by,&_i)=%scan(&by,&_i)_ORIG;
        %let by_created   = %left(&by_created) %scan(&by,&_i)=put(%scan(&by,&_i)_ORIG,%left(&&byfmt&_i))%str(;);
        %let by_orig      = %left(&by_orig) %scan(&by,&_i)_ORIG;
        %let by_sort      = %left(&by_sort) %scan(&by,&_i)_ORIG;
      %end;
      %else %let by_sort  = %left(&by_sort) %scan(&by,&_i); * To sort by-categories by unformatted values *;
    quit;
  %end;
  %let by_created=%sysfunc(tranwrd(&by_created,%str( ),%str(; )));
  %put NOTE: &=by_formatted; * AVISITN *;
  %put NOTE: &=by_formats;   * vis.    *;
  %put NOTE: &=by_renamed;   * AVISITN=AVISITN_ORIG *;
  %put NOTE: &=by_created;   * AVISITN=put(AVISITN_ORIG,vis.); *;
  %put NOTE: &=by_orig;      * AVISITN_ORIG *;

  %local trtfmt catfmt;
  proc sql noprint;
    select FORMAT into :trtfmt trimmed from sashelp.VCOLUMN where LIBNAME='WORK' and upcase(MEMNAME)=upcase("&inds") and upcase(NAME)=upcase("&trt");
    select FORMAT into :catfmt trimmed from sashelp.VCOLUMN where LIBNAME='WORK' and upcase(MEMNAME)=upcase("&inds") and upcase(NAME)=upcase("&cat");
  quit;
  %put NOTE: &=trtfmt &=catfmt;

  * Process by-variables with preload format to keep _orig variables for sorting purpose *;
  %if %length(&by_formatted.)>0 %then %do;
    data &inds._C1;
      set &inds._C1;
      %do _i=1 %to %sysfunc(countw(&by_formatted.));
        %scan(&by_orig.,&_i.) = %scan(&by_formatted.,&_i.); * Create copy of the original variable *;
      %end;
    run;
  %end;

  proc summary data=&inds._C1 nway completetypes missing;
    %if %length(&by)>0 %then %do _i=1 %to %sysfunc(countw(&by.)); class %scan(&by,&_i) %if %length(&&byfmt&_i)>0 %then / preloadfmt mlf;; %end; * Cycle through BYVARs *;
    class &trt. %if %length(&trtfmt.)>0 %then / preloadfmt mlf;; * TRTVAR *;
    class &cat. %if %length(&catfmt.)>0 %then / preloadfmt mlf;; * CATVAR *;
    var _COUNTERN;
    output out=&inds._C2N(drop=_type_ _freq_) n=N;
  run;
  proc summary data=&inds._C1 nway completetypes missing;
    %if %length(&by)>0 %then %do _i=1 %to %sysfunc(countw(&by.)); class %scan(&by,&_i) %if %length(&&byfmt&_i)>0 %then / preloadfmt mlf;; %end; * Cycle through BYVARs *;
    class &trt. %if %length(&trtfmt.)>0 %then / preloadfmt mlf;; * TRTVAR *;
    class &cat. %if %length(&catfmt.)>0 %then / preloadfmt mlf;; * CATVAR *;
    var _COUNTERE;
    output out=&inds._C2E(drop=_type_ _freq_) n=E;
  run;
  %if &c1cnt=0 %then %do;
  proc sql;
    update &inds._C2N set N=0;
    update &inds._C2E set E=0;
  quit;
  %end;
  proc sort data=&inds._C2N(where=(input(&trt.,?best.) in (&_default_trt_seq.))); by &cat. &by. &trt.; run;
  proc sort data=&inds._C2E(where=(input(&trt.,?best.) in (&_default_trt_seq.))); by &cat. &by. &trt.; run;
  proc transpose data=&inds._C2N(where=(compress(&cat.)^=".")) out=&inds._C2NT(drop=_:) prefix=&prefn.;
    by &cat. &by.;
    id &trt.;
    var N;
  run;
  proc transpose data=&inds._C2E(where=(compress(&cat.)^=".")) out=&inds._C2ET(drop=_:) prefix=&prefe.;
    by &&cat. &by.;
    id &trt.;
    var E;
  run;
  data &inds._C3;
    merge &inds._C2NT &inds._C2ET;
    by &cat. &by.;
    retain ORD 0;
    if first.&cat. then ORD+1;
    %if not %index(%upcase(&stat),N) %then drop &prefn.:;;
    %if not %index(%upcase(&stat),E) %then drop &prefe.:;;
  run;
  %if &c1cnt=0 and %length(&catfmt.)=0 %then %do; * Drop blank record if there were no data and no records were created due to missing preload format *;
  proc sql;
    delete from &inds._C3;
  quit;
  %end;
  %row(inds=&inds., outds=&inds._C4, where=&where., sec=&sec., ord=0, trt=&trt., by=&by., lbl=&lbl., stat=&stat., prefn=&prefn., prefe=&prefe., dropds=&dropds.);
  data &outds.(drop=&cat.);
    set &inds._C4(in=a) &inds._C3(in=b);
    SEC=&sec.;
    if b then LABEL = &cat.;
  run;
  %if %length(&catfmt.)>0 %then %do;
    proc format cntlout=_CATFMT(where=(upcase(FMTNAME)=upcase(compress("&catfmt",'.')) and TYPE in ('N' 'C')));
    run;
    data _CATFMT(keep=LABEL FMTORD);
      set _CATFMT;
      FMTORD = input(strip(START),best.);
    run;
    proc sql; create table &inds._C5 as select a.*, FMTORD from &outds. as a left join _CATFMT as b on a.LABEL=b.LABEL order by FMTORD; quit;
    data &outds.(drop=FMTORD);
      set &inds._C5;
      if FMTORD then ORD=FMTORD;
    run;
    %if %upcase(&dropds)=Y %then %do; proc sql; drop table &inds._C5, _CATFMT; quit; %end;
  %end;
  * Add unformatted by-variables for sorting purpose *;
  %if %length(&by_formatted.)>0 %then %do _i=1 %to %sysfunc(countw(&by_formatted.));
    %put NOTE: Add unformatted BY-variable %scan(&by_orig.,&_i.,)[%scan(&by_formats.,&_i.,)] for sorting purposes.;
    proc format cntlout=_FMT_(where=( strip(upcase(FMTNAME))||"."="%scan(&by_formats.,&_i.,)" ) keep=FMTNAME START LABEL); run;
    data _FMT_; set _FMT_; %scan(&by_orig.,&_i.,) = input(START,%scan(&by_formats.,&_i.,)); rename LABEL=%scan(&by_formatted.,&_i.,); run;
    proc sql;
      create table _TMP_ as select a.*, b.%scan(&by_orig.,&_i.,)
        from &outds.(drop=%scan(&by_orig.,&_i.,)) as a left join _FMT_ as b on a.%scan(&by_formatted.,&_i.,)=b.%scan(&by_formatted.,&_i.,);
    quit;
    data &outds.; set _TMP_(where=(n(%scan(&by_orig.,&_i.,)))); run;
    proc sql noprint; drop table _TMP_, _FMT_; quit;
  %end;
  %if %upcase(&dropds)=Y %then %do; proc sql; drop table &inds._C1, &inds._C2N, &inds._C2E, &inds._C2NT, &inds._C2ET, &inds._C3, &inds._C4; quit; %end;
%mend cat;

* Macro to create nested counts (multiple categories with subcategories) *;
%macro nst(inds,where,outds,by,trt,cat,scat,highlow=,sec=1,dropds=Y,stat=N,prefn=TRT_N_,prefe=TRT_E_,trtlist=&_default_trt_seq.);
  * by - additional by-variables, cat\scat - categorical variables, lbl - variable for first (summary) row, highlow - H\L to count patient only once in highest or lowest category *;
  * stat, prefn, prefe - same as in CAT *;
  %if %length(&trt)=0 %then %put %str(WAR)NING: Parameter TRT is blank, please pass the value (numeric variable).;
  %if %length(&cat)=0 %then %put %str(WAR)NING: Parameter CAT is blank, please pass the name of the categorical variable.;
  %if %length(&scat)=0 %then %put %str(WAR)NING: Parameter SCAT is blank, please pass the name of the categorical variable.;
  %if %length(&sec)=0 %then %let sec=1;
  %if %length(&outds)=0 %then %let outds=SEC_&sec._NST;
  %let sql_by = %upcase(%sysfunc(tranwrd(%sysfunc(compbl(%str(&by))),%str( ),%str(,))));
  proc sort data=&inds. out=&inds._N1(where=(cmiss(&trt.)=0)); by &by. &trt. USUBJID &cat. &scat.; run;
  %let catlst=;
  %let nestlst=;
  %let droplst=;
  proc sql noprint;
    update &inds._N1 set &cat.="UNCODED" where missing(&cat.);
    update &inds._N1 set &scat.="UNCODED" where missing(&scat.);
    select distinct &cat. into :catlst separated by "|" from &inds._N1 %if %length(&where)>0 %then %do; where &where. %end; order by &cat.;
  quit;
  %put NOTE: &=catlst;
  %if &sqlobs.>0 %then %do _n=1 %to %eval(%sysfunc(countc(%superq(catlst),|))+1);
    %let lbl=%qscan(%superq(catlst),&_n,|);
    %put NOTE: &_n.. Process category &=lbl;
    %cat(inds=&inds._N1, where=%if %length(&where)>0 %then %do; &where. and %end; &cat.=strip("&lbl"), outds=&inds._N1_%left(&_n.), by=&by., trt=&trt., cat=&scat., lbl=strip("&lbl"), sec=&_n., highlow=&highlow., stat=&stat., prefn=&prefn., prefe=&prefe.);
    %let nestlst=%left(&nestlst) &inds._N1_%left(&_n.)(rename=(ORD=ORD2 SEC=ORD));
    %let droplst=%left(&droplst) &inds._N1_%left(&_n.);
  %end;
  %else %do;
    data &inds._N1_ND;
      length LABEL $200;
      LABEL="No data for this subset";
      %do _n=1 %to %sysfunc(countw(&trtlist.)); &prefn.%scan(&trtlist.,&_n.)=.; %end;
      ORD  = 1;
      ORD2 = 1;
    run;
    %let nestlst=&inds._N1_ND;
    %let droplst=&inds._N1_ND;
  %end;
  data &inds._N2;
    set &nestlst.;
    SEC=&sec.;
  run;
  proc sort data=&inds._N2 out=&outds.; by SEC ORD ORD2; run;
  %if %upcase(&dropds)=Y %then %do; %put NOTE: &=droplst.; proc sql; drop table %sysfunc(tranwrd(&droplst,%str( ),%str(,))); quit; %end;
%mend nst;

* Macro to get BigN counts for npcnt macro *;
%macro bign(inds,where,by,trt,outds,dropds=Y);
  %if %length(&outds)=0 %then %let outds=BIGN;
  %row(inds=&inds., where=&where., outds=&outds., by=&by., trt=&trt., lbl="BIGN", stat=N, dropds=&dropds.);
  proc sql noprint; select catx("=",NAME,cats("BIGN_",compress(NAME,,'kd'))) into :renvars separated by " " from sashelp.VCOLUMN where LIBNAME='WORK' and upcase(MEMNAME)=upcase("&outds.") and NAME like "TRT_%"; quit;
  data &outds.;
    set &outds.;
    rename &renvars.;
    drop LABEL SEC ORD;
  run;
%mend bign;

* Macro to calculate percentage and create "nn (pp.p%)" values for ROW and CAT results *;
%macro npcnt(inds, outds, bign, by, pcntwhere=1, type=1, pct=N, miss2zero=Y, zerowhere=1, dropds=Y);
  * bign - dataset with Big N (population) counts, pcntwhere - condition for rows where percentage should be added,
    type - type of N_PCNT_X values: 1 = nn (pp.p%), 2 = nn ee (pp.p%), 3 = nn (pp.p%) ee, pct - if Y then add percent sign after the value *;
  %if %length(&pcntwhere)=0 %then %let pcntwhere=1;
  %if %length(&zerowhere)=0 %then %let zerowhere=1;
  %if %length(&outds)=0 %then %let outds=&inds._NPCNT;
  %let sql_by = %upcase(%sysfunc(tranwrd(%sysfunc(compbl(%str(&by))),%str( ),%str(,))));
  %if %upcase(&pct.)=Y %then %let pctsgn=%str(%%); %else %let pctsgn=;
  proc sort data=&inds. out=&inds._NPCNT1; by &by. SEC ORD; run;
  %if %sysfunc(exist(&bign)) %then %do; * If dataset with name provided in parameter bign  exist, then use it to calculate percentage, otherwise we will use varaible name in input dataset *;
  proc sort data=&bign. out=&inds._NPCNT2; by &by. _all_; run;
    %if %length(&by)>0 %then %do;
      data &inds._NPCNT3;
        merge &inds._NPCNT1(in=a) &inds._NPCNT2(in=b);
        if a;
        by &by.;
      run;
    %end;
    %else %do;
      proc sql; create table &inds._NPCNT3 as select * from &inds._NPCNT1, &inds._NPCNT2; quit;
    %end;
  %end; %else %do;
    proc sql noprint;
      select upcase(tranwrd(NAME,"TRT_N_","BIGN_")) into :new_bign separated by " " from sashelp.VCOLUMN where LIBNAME='WORK' and upcase(MEMNAME)=upcase("&inds._NPCNT1") and NAME like 'TRT_N_%';
    quit;
    data &inds._NPCNT2;
      set &inds._NPCNT1;
    run;
    data &inds._NPCNT3;
      set &inds._NPCNT1;
      %do _i=1 %to %sysfunc(countw(&new_bign.));
        %let bignvar=%scan(&new_bign,&_i);
        %if %sysfunc(tranwrd(&bignvar.,BIGN_,TRT_N_))=%upcase(&bign.) %then %do; &bignvar.=.; %end;
        %else %do; &bignvar.=&bign.; %end;
      %end;
    run;
  %end;
  %local lst_n lst_e lst_bign;
  proc sql noprint;
    select upcase(NAME), input(compress(NAME,,'kd'),?best.) as _N into :lst_n separated by " ", :_ from sashelp.VCOLUMN where LIBNAME='WORK' and upcase(MEMNAME)=upcase("&inds._NPCNT3") and NAME like 'TRT_N_%' order by _N;
    select upcase(NAME), input(compress(NAME,,'kd'),?best.) as _N into :lst_e separated by " ", :_ from sashelp.VCOLUMN where LIBNAME='WORK' and upcase(MEMNAME)=upcase("&inds._NPCNT3") and NAME like 'TRT_E_%' order by _N;
    select upcase(NAME), input(compress(NAME,,'kd'),?best.) as _N into :lst_bign separated by " ", :_ from sashelp.VCOLUMN where LIBNAME='WORK' and upcase(MEMNAME)=upcase("&inds._NPCNT3") and NAME like 'BIGN_%' order by _N;
  quit;
  %put NOTE: &=lst_n;
  %put NOTE: &=lst_e;
  %put NOTE: &=lst_bign;
  data &outds.;
    set &inds._NPCNT3;
    %if %length(&lst_n)>0 %then %do _i=1 %to %sysfunc(countw(&lst_n));
      %let NVAR = %scan(&lst_n, &_i);
      %let EVAR = %scan(&lst_e, &_i);
      %let BIGNVAR = %scan(&lst_bign, &_i);
      %let PVAR = %sysfunc(tranwrd(&nvar,TRT_N_,PCNT_));
      %let NPVAR = %sysfunc(tranwrd(&nvar,TRT_N_,N_PCNT_));
      %if %upcase(&miss2zero)=Y %then %do; if (&zerowhere.) and missing(&nvar.) then &nvar.=0; %end;
      length &npvar. $200;
      if &npvar. = "" then &npvar. = "";
      if (&pcntwhere.) then do;
        if n(&nvar.) and &bignvar. then &pvar.=round(&nvar.*100/&bignvar.,.1);
        %if &type=1 %then %do; if missing(&npvar.) then &npvar. = put(&nvar.,6.)||ifc(&pvar.," ("||put(&pvar.,5.1)||"&pctsgn)",""); %end;
        %if &type=2 %then %do; if missing(&npvar.) then &npvar. = put(&nvar.,6.)||put(&evar.,6.)||tranwrd(ifc(&pvar.," ("||put(&pvar.,5.1)||"&pctsgn)",""),"100.0","100"); %end;
        %if &type=3 %then %do; if missing(&npvar.) then &npvar. = put(&nvar.,6.)||tranwrd(ifc(&pvar.," ("||put(&pvar.,5.1)||"&pctsgn)",""),"100.0","100")||put(&evar.,6.); %end;
        do while(index(&npvar.,"( ")); &npvar. = tranwrd(&npvar.,"( "," ("); end;
      end;
      else do;
        %if &type=1 %then %do; if missing(&npvar.) then &npvar. = put(&nvar.,6.); %end;
        %if &type=2 %then %do; if missing(&npvar.) then &npvar. = put(&nvar.,6.)||put(&evar.,4.); %end;
        %if &type=3 %then %do; if missing(&npvar.) then &npvar. = put(&nvar.,6.)||put(&evar.,4.); %end;
      end;
      &npvar. = tranwrd(strip(compbl(&npvar.)),"0 0","0"); * Normalize *;
    %end;
  run;
  %if %upcase(&dropds)=Y %then %do; proc sql; drop table &inds._NPCNT1,&inds._NPCNT2, &inds._NPCNT3; quit; %end;
%mend npcnt;

* Get maximal number of DP for specified subset, can be used in STC *;
%macro get_prec(inds,where,var,outds,outmvar);
  %if %length(&var)=0 %then %put %str(WAR)NING: Parameter INDS is blank, please pass the value (dataset name).;
  %if %length(&var)=0 %then %put %str(WAR)NING: Parameter VAR is blank, please pass the value (numeric variable).;
  %if %length(&where)=0 %then %let where=1;
  %if %length(&outds)=0 %then %let outds=&inds._PREC;
  * Check preload format for TRT and get precision for VAR *;
  proc sql noprint;
    %let prec_orig=0;
    create table &outds. as select distinct max(length(strip(put(int(&var.),?best.)))) as int_orig, max(length(strip(put(abs(&var.)-int(abs(&var.)),?best.))))-2 as prec_orig
      from &inds.(where=((&where) and not missing(&var.)));
    %if %length(&outmvar)>0 and %sysfunc(anyalpha(%str( &outmvar ))) %then %do;
      %global &outmvar.;
      select prec_orig into :&outmvar. trimmed from &outds.;
      %put NOTE: &outmvar=&&&outmvar;
    %end;
  quit;
%mend;

* Macro to get N MEAN SD MEANSD MEDIAN Q1 Q3 Q1Q3 IQR MIN MAX MINMAX CI95 counts *;
%macro stc(inds,where,outds,by,trt,var,lbl,highlow=,sec=1,dropds=Y,statlst=,ci95lev=2,prchg=0,prset=);
  * by - additional by-variables, var - variable to be counted, lbl - variable for first (summary) row, highlow - H\L to count patient only once in highest or lowest category,
    statlst - list and order of required statistics\counts, ci95lev - level for proportion,  
    prchg - change precision from the level based on the data precision (eg +2 or -1), prset - set manual precision (eg 1 or 4)*;
  %if %length(&trt)=0 %then %put %str(WAR)NING: Parameter TRT is blank, please pass the value (numeric variable).;
  %if %length(&var)=0 %then %put %str(WAR)NING: Parameter VAR is blank, please pass the value (numeric variable).;
  %if %length(&sec)=0 %then %let sec=1;
  %if %length(&outds)=0 %then %let outds=SEC_&sec._STC;
  %if %length(&statlst)=0 %then %let statlst=N MEANSD MEDIAN Q1Q3 MINMAX;
  %else %let statlst=%upcase(%sysfunc(compbl(&statlst)));
  %let statlst2 = %sysfunc(tranwrd("&statlst",%str( ),%str(",")));
  %let sql_by = %upcase(%sysfunc(tranwrd(%sysfunc(compbl(%str(&by))),%str( ),%str(,))));
  %if not %index(%nrbquote(&lbl),%str(%")) %then %let lbl="&lbl";
  proc sort data=&inds.%if %length(&where)>0 %then %do;(where=(&where.))%end; out=&inds._S1; by &by. &trt. USUBJID &var.; run;
  data &inds._S1;
    set &inds._S1(where=(cmiss(&trt.)=0));
    by &by. &trt. USUBJID;
    %if %upcase(&highlow)=H %then if not last.USUBJID  then delete; * if H then process only highest value if there are multiple records;
    %if %upcase(&highlow)=L %then if not first.USUBJID then delete; * if L then process only lowest  value if there are multiple records;
  run;
  * Workaround for case when there are no records per current condition *;
  %let S1CNT=0;
  proc sql noprint;
    select distinct &trt. into :TRTLST separated by " " from &inds. order by &trt.;
    select count(*) into :S1CNT trimmed from &inds._S1;
  quit;
  %put NOTE: &=s1cnt &=trtlst;
  %if &s1cnt=0 %then %do;
    data &inds._S1;
      set &inds.;
      if _N_=1;
      call missing(of _all_);
      %do _i=1 %to %sysfunc(countw(&trtlst.));
        &trt. = %scan(&trtlst.,&_i.);
        output;
      %end;
    run;
  %end;
  * ^^^ *;

  * Check preload formats for by-variables *;
  %local trtfmt by_formatted by_formats by_renamed by_created by_orig by_sort;
  %if %length(&by.)>0 %then %do _i=1 %to %sysfunc(countw(&by.));
    %let byfmt&_i=;
    proc sql noprint;
      select FORMAT into :byfmt&_i trimmed from sashelp.VCOLUMN where LIBNAME='WORK' and upcase(MEMNAME)=upcase("&inds") and upcase(NAME)=upcase("%scan(&by,&_i)");
      %if %length(&&byfmt&_i)>0 %then %do;
        %put NOTE: Preload format identified for BY-variable %scan(&by,&_i): &&byfmt&_i;
        %let by_formatted = %left(&by_formatted) %scan(&by,&_i);
        %let by_formats   = %left(&by_formats) %left(&&byfmt&_i);
        %let by_renamed   = %left(&by_renamed) %scan(&by,&_i)=%scan(&by,&_i)_ORIG;
        %let by_created   = %left(&by_created) %scan(&by,&_i)=put(%scan(&by,&_i)_ORIG,%left(&&byfmt&_i))%str(;);
        %let by_orig      = %left(&by_orig) %scan(&by,&_i)_ORIG;
        %let by_sort      = %left(&by_sort) %scan(&by,&_i)_ORIG;
      %end;
      %else %let by_sort  = %left(&by_sort) %scan(&by,&_i); * To sort by-categories by unformatted values *;
    quit;
  %end;

  %let by_created=%sysfunc(tranwrd(&by_created,%str( ),%str(; )));
  %put NOTE: &=by_formatted;
  %put NOTE: &=by_formats;
  %put NOTE: &=by_renamed;
  %put NOTE: &=by_created;
  %put NOTE: &=by_orig;
  * Check preload format for TRT and get precision for VAR *;
  proc sql noprint;
    %let int_orig=5;
    %let prec_orig=0;
    select FORMAT into :trtfmt trimmed from sashelp.VCOLUMN where LIBNAME='WORK' and upcase(MEMNAME)=upcase("&inds") and upcase(NAME)=upcase("&trt");
    %if %length(&trtfmt)>0 %then %put NOTE: Preload format identified for TRT variable &trt: &trtfmt;
    create table &inds._SPREC as select distinct
        %if %length(&by.)>0 %then &sql_by.,; max(length(strip(put(int(&var.),?best.)))) as int_orig, max(length(strip(put(abs(&var.)-int(abs(&var.)),?best.))))-2 as prec_orig
      from &inds._S1(where=(not missing(&var.))) %if %length(&by.)>0 %then group by &sql_by.;;
  quit;
  %put NOTE: &=int_orig, &=prec_orig;
  data &inds._SPREC;
    set &inds._SPREC;
    INT_ORIG = max(INT_ORIG,1)+1; * +1 is for negatives *;
    %if %sysfunc(anydigit(%str( &prset. ))) %then %do; PREC_ORIG = &prset.; %end;
    %else %do; PREC_ORIG = max(PREC_ORIG,0)+(&prchg.); %end;
    PREC1 = catx(".",INT_ORIG+PREC_ORIG+1,PREC_ORIG);
    PREC2 = catx(".",INT_ORIG+PREC_ORIG+2,PREC_ORIG+1);
    PREC3 = catx(".",INT_ORIG+PREC_ORIG+3,PREC_ORIG+2);
  run;

  * Process by-variables with preload format to keep _orig variables for sorting purpose *;
  %if %length(&by_formatted.)>0 %then %do;
    data &inds._S1;
      set &inds._S1;
      %do _i=1 %to %sysfunc(countw(&by_formatted.));
        %scan(&by_orig.,&_i.) = %scan(&by_formatted.,&_i.); * Create copy of the original variable *;
      %end;
    run;
  %end;

  proc summary data=&inds._S1 nway completetypes missing;
    %if %length(&by)>0 %then %do _i=1 %to %sysfunc(countw(&by.)); class %scan(&by,&_i) %if %length(&&byfmt&_i)>0 %then / preloadfmt mlf;; %end; * Cycle through BYVARs *;
    class &trt. %if %length(&trtfmt.)>0 %then / preloadfmt mlf;; * TRTVAR *;
    var &var.;
    output out=&inds._S2(drop=_type_ _freq_) N=_N MEAN=_MEAN STD=_SD MEDIAN=_MEDIAN Q1=_Q1 Q3=_Q3 MIN=_MIN MAX=_MAX LCLM=_LCLM UCLM=_UCLM;
  run;

  proc sql noprint; select count(distinct &var.) into :VARLEVELS trimmed from &inds._S1; quit;
  %put NOTE: &=varlevels;
  %if %index(%upcase(&statlst.),%str(CI95)) and &varlevels.>1 %then %do;
    * Add CI95 from proc freq (binomial and exact binomial) *;
    data &inds._S2BIN; length &by. &trt. NAME1 LABEL1 CVALUE1 $200; call missing(of _all_); run;
    ods listing close;
    ods results off;
    proc freq data=&inds._S1;
     by &by. &trt.;
     tables &var. / binomial(level=&ci95lev.) alpha=0.05;
     ods output binomial=&inds._S2BIN(keep=&by. &trt. NAME1 LABEL1 CVALUE1);
    run;
    ods results on;
    ods listing;
    proc transpose data=&inds._S2BIN(where=(NAME1 in ("L_BIN" "U_BIN" "XL_BIN" "XU_BIN"))) out=&inds._S2BINT(drop=_:);
      by &by. &trt.;
      var CVALUE1;
      id NAME1;
    run;

    data &inds._S2;
      set &inds._S2;
      length _KEY $1000;
      _KEY=catx( " ", %sysfunc(tranwrd(%sysfunc(compbl(&by. &trt.)),%str( ),%str(,))) );
    run;
    data &inds._S2BINT;
      set &inds._S2BINT;
      length _KEY $1000;
      _KEY=catx( " ", %sysfunc(tranwrd(%sysfunc(compbl(&by. &trt.)),%str( ),%str(,))) );
    run;
    data &inds._S2(drop=_KEY);
      merge &inds._S2(in=a) &inds._S2BINT(in=b drop=&by. &trt.);
      by _KEY;
      if a;
      format _all_;
    run;

    %if %upcase(&dropds)=Y %then %do; proc sql; drop table &inds._S2BIN, &inds._S2BINT; quit; %end;
  %end;
  
  %let sqlby=;
  %if %length(&by.)>0 %then %do;
    %let sqlby=a.%scan(&by,1)=b.%scan(&by,1);
    %if %sysfunc(countw(&by.))>1 %then %do _i=2 %to %sysfunc(countw(&by.));
      %let sqlby = &sqlby and a.%scan(&by,&_i)=b.%scan(&by,&_i);
    %end;
    %put NOTE: &=sqlby;
  %end;

  * Process by-variables with preload format (converted in proc summary and kept as is in precision code *;
  %if %length(&by_formatted.)>0 %then %do;
    %put NOTE: transform by-variables with preload format;
    data &inds._SPREC;
      set &inds._SPREC(rename=(&by_renamed.));
      &by_created.;
    run;
  %end;

  proc sql;
    create table &inds._S3 as select a.*, b.PREC1, b.PREC2, b.PREC3
      from &inds._S2 as a %if %length(&by.)>0 %then left; %else cross; join &inds._SPREC as b %if %length(&by.)>0 %then on &sqlby.;;
  quit;
  data &inds._S3;
    set &inds._S3;
    length N MEAN SD MEANSD MEDIAN Q1 Q3 Q1Q3 IQR MIN MAX MINMAX CI95 CI95B CI95X $200;
    label N="n" MEAN="Mean" SD="SD" MEANSD="Mean (SD)" MEDIAN="Median" Q1="Q1" Q3="Q3" Q1Q3="Q1, Q3" IQR="IQR" MIN="Min" MAX="Max" MINMAX="Min, Max" CI95="95% CI" CI95B="95% CI" CI95X="95% CI";
    if n(_N)    then N      = put(_N      ,best.);
    if n(_MEAN) then MEAN   = putn(_MEAN  ,PREC2);
    if n(_SD)   then SD     = putn(_SD    ,PREC3);
    MEANSD = strip(MEAN)||" ("||strip(SD)||")";
    if n(_MEDIAN) then MEDIAN = putn(_MEDIAN,PREC2);
    if n(_Q1)   then Q1     = putn(_Q1    ,PREC2);
    if n(_Q3)   then Q3     = putn(_Q3    ,PREC2);
    Q1Q3   = strip(Q1)||", "||strip(Q3);
    if cmiss(_Q1,_Q3)=0 then IQR    = putn(_Q3-_Q1,PREC2);
    if n(_MIN)  then MIN    = putn(_MIN   ,PREC1);
    if n(_MAX)  then MAX    = putn(_MAX   ,PREC1);
    MINMAX = strip(MIN)||", "||strip(MAX);
    if _LCLM=. then _LCLM=.;
    if _UCLM=. then _UCLM=.;
    if L_BIN=. then L_BIN=.;
    if U_BIN=. then U_BIN=.;
    if XL_BIN=. then XL_BIN=.;
    if XU_BIN=. then XU_BIN=.;
    if cmiss(_LCLM,_UCLM)=0 then CI95    = "["||strip(putn(_LCLM,PREC2)) ||"; "||strip(putn(_UCLM,PREC2)) ||"]";
    %if (%index(%upcase(&statlst.),%str(CI95B)) or %index(%upcase(&statlst.),%str(CI95X))) %then %do;
      %if &varlevels.>1 %then %do;
        if cmiss(L_BIN,U_BIN)=0 then CI95B   = "["||strip(putn(L_BIN,PREC2)) ||"; "||strip(putn(U_BIN,PREC2)) ||"]";
        if cmiss(XL_BIN,XU_BIN)=0 then CI95X   = "["||strip(putn(XL_BIN,PREC2))||"; "||strip(putn(XU_BIN,PREC2))||"]";
      %end;
      %else %do;
        CI95B = " ";
        CI95X = " ";
      %end;
    %end;
  run;
  proc sort data=&inds._S3(where=(input(&trt.,?best.) in (&_default_trt_seq.))); by &by. &trt.; run;
  proc transpose data=&inds._S3 out=&inds._S4(rename=(_LABEL_=LABEL)) prefix=N_PCNT_;
    %if %length(&by.)>0 %then by &by.;;
    id &trt.;
    var N MEAN SD MEANSD MEDIAN Q1 Q3 Q1Q3 IQR MIN MAX MINMAX CI95 CI95B CI95X;
  run;
  data &outds.(drop=i _NAME_);
    length LABEL $200;
    set &inds._S4(in=a) &inds._S4(in=b);
    array NP{*} N_PCNT_:;
    SEC=&sec.;
    if a then do; if _N_=1; LABEL=&lbl.; call missing(of N_PCNT_:); end;
    if b then do;
      ORD = whichc(_NAME_, &statlst2.);
      if not ORD then delete;
    end;
    do i=1 to hbound(NP);
      if compress(NP{i}) in ("()" ",", "(,)", "(;)") then call missing(NP{I});
      else NP{i}=tranwrd(strip(NP{i}),"()","(NA)");
    end;
  run;
  * Add unformatted by-variables for sorting purpose *;
  %if %length(&by_formatted.)>0 %then %do _i=1 %to %sysfunc(countw(&by_formatted.));
    %put NOTE: Add unformatted BY-variable %scan(&by_orig.,&_i.,)[%scan(&by_formats.,&_i.,)] for sorting purposes.;
    proc format cntlout=_FMT_(where=( strip(upcase(FMTNAME))||"."="%scan(&by_formats.,&_i.,)" ) keep=FMTNAME START LABEL); run;
    data _FMT_; set _FMT_; %scan(&by_orig.,&_i.,) = input(START,%scan(&by_formats.,&_i.,)); rename LABEL=%scan(&by_formatted.,&_i.,); run;
    proc sql;
      create table _TMP_ as select a.*, b.%scan(&by_orig.,&_i.,)
        from &outds. as a left join _FMT_ as b on a.%scan(&by_formatted.,&_i.,)=b.%scan(&by_formatted.,&_i.,);
    quit;
    data &outds.; set _TMP_; run;
    proc sql noprint; drop table _TMP_, _FMT_; quit;
  %end;
  %if %upcase(&dropds)=Y %then %do; proc sql; drop table &inds._S1, &inds._S2, &inds._S3, &inds._S4, &inds._SPREC; quit; %end;
%mend stc;

* Add blank row with label *;
%macro lbl(outds,lbl,sec=1,ord=0,dropds=Y,prefn=TRT_N_,trtlist=&_default_trt_seq);
  %if %length(&outds)=0   %then %let outds=sec_&sec._lbl_&ord.;
  %if not %index(%nrbquote(&lbl),%str(%")) %then %let lbl="&lbl";
  %if %length(&sec)=0     %then %let sec=1;
  %if %length(&ord)=0     %then %let ord=0;
  %if %length(&trtlist)=0 %then %put %str(WAR)NING: Parameter TRTLIST is blank, please pass the value (trt numbers).;
  %if %length(&prefn)=0   %then %let prefn=TRT_N_;
  data &outds.;
    length LABEL $200;
    LABEL = &lbl.;
    %do _i=1 %to %sysfunc(countw(&trtlist.)); &prefn.%scan(&trtlist.,&_i.)=.; %end;
    SEC=&sec.;
    ORD=&ord.;
  run;
%mend lbl;

* Add new rows with labels for by-groups*;
%macro bylbl(inds=,outds=,by=,pref=N_PCNT_,ord=-1);
  %if %length(&outds)=0 %then %let outds=&inds._bylbl;
  %if %length(&by)=0    %then %put %str(WAR)NING: Parameter BY is blank, please pass the name.;
  proc sort data=&inds. out=&outds.; by SEC &by.; run;
  data &outds.;
    set &outds.;
    by SEC &by.;
    if first.&by. then do;
      output; * Original row *;
      LABEL=&by.;
      ORD=&ord.;
      call missing(of &pref.:);
      output; * Label row *;
    end;
    else output;
  run;
  proc sort data=&outds.; by SEC &by. ORD:; run;
%mend bylbl;

* Reorder rows within sections *;
%macro ord(inds=, outds=, where=, neword=, keepord=0, keepsec=13011982, dropds=Y);
  * neword - list of variables to be used to reorder rows (for example TRT_N_99 desc), keepord - original ORD values which will be kept as is *;
  %if %length(&outds)=0  %then %let outds=&inds._ORD;
  %if %length(&neword)=0 %then %put %str(WAR)NING: Parameter NEWORD is blank, please specify new sort order.;
  proc sort data=&inds. out=&inds._O1; by SEC &neword.; run;
  data &inds._O2;
    set &inds._O1;
    by SEC &neword.;
    retain _NEWORD_;
    if first.SEC then _NEWORD_=1;
    else _NEWORD_+1;
    if ORD not in (&keepord.) and SEC not in (&keepsec.) then ORD = _NEWORD_;
  run;
  proc sort data=&inds._O2 out=&outds.(drop=_NEWORD_); by SEC ORD; run;
  %if %upcase(&dropds)=Y %then %do; proc sql; drop table &inds._O1, &inds._O2; quit; %end;
%mend ord;

* Convert validation dataset (variables N_PCNT_xx) to be ready for comparison with main dataset (variables COLx) *;
%macro prepval(inds, outds, vars, suppress);
  %if %length(&outds.)=0 %then %let outds=v_&pgmid.;
  %if %length(&vars.)=0 %then %do;
    %let npvars=;
    proc sql noprint;
      select NAME, input(compress(NAME,,'kd'),?best.) as _N into :npvars separated by " ", :_ from sashelp.VCOLUMN where LIBNAME='WORK' and upcase(MEMNAME)=upcase("&inds.") and NAME like 'N_PCNT_%' order by _N;
    quit;
    %let vars=LABEL &npvars;
  %end;
  %put NOTE: &=vars;
  %let renvars=;
  %do _i=1 %to %sysfunc(countw(&vars.));
    %let var=%scan(&vars,&_i);
    %let renvars=&renvars &var=COL&_i;
  %end;
  %put NOTE: &=renvars;
  data &outds.; * Reorder columns *;
    retain &vars.;
    set &inds.;
    %if %index(%str( &vars ), %str( LABEL )) %then %do; label LABEL=" "; %end;
    %if %length(&suppress)>0 %then %do;
      array S{*} &suppress.;
      do i=1 to hbound(S);
        if S{i}=lag(S{i}) then do;
          if i=1 then call missing(S{i});
          else if i>1 then if missing(S{i-1}) then call missing(S{i});
        end;
      end;
    %end;
  run;
  data &outds.(keep=COL:);
    length COL1-COL%sysfunc(countc(&renvars.,%str(=))) $200;
    set &outds.(rename=(&renvars.));
  run;
  proc datasets lib=work memtype=data nodetails nolist;
     modify &outds.;
     attrib _all_ label=' ';
     *attrib _all_ format=;
  quit;
%mend prepval;

* Compare main and validation datasets *;
%macro compval(id);
  %if %upcase(%substr(&id,1,1))=T %then %let lib=tabdat;
  %else %if %upcase(%substr(&id,1,1))=L %then %let lib=lstdat;
  %else %if %upcase(%substr(&id,1,1))=F %then %let lib=figdat;
  %else %put %str(WAR)NING: Unexpected ID=%left(&id).;
  data DEV(keep=COL:);
    set &lib..&id.;
    array C{*} COL:;
    do i=1 to hbound(C);
      C{i}=strip(compbl(tranwrd(C{i},"@w","")));
      C{i}=strip(compbl(tranwrd(C{i},"@n","")));
    end;
  run;
  proc datasets lib=work memtype=data nodetails nolist;
     modify DEV;
     attrib _all_ label=' ';
     *attrib _all_ format=;
  quit;
  data v_&lib..v_&pgmid.;
    set v_&pgmid.;
  run;
  data VAL(drop=i);
    set v_&pgmid.;
    array C{*} COL:;
    do i=1 to hbound(C);
      C{i}=strip(compbl(tranwrd(C{i},"@w","")));
    end;
  run;
  proc compare base=DEV comp=VAL;
  run;
%mend compval;

* Macro to produce table output - test *;
%macro reptbl(inds,ttl=,pop=,src=,colwidth=,esc=%str(@),split=%str(~));
  * inds - output dataset with variables COL1-COLx, colwidth - width for each column in % separated by spaces *;
  options papersize=letter orientation=landscape nodate nonumber center missing=" " nobyline; 
  ods escapechar="&esc"; 
  ods listing close;

  %mstrtrtf(pgmname=&pgmname, pgmid=1);
  %let dttm=%sysfunc(putn(%sysfunc(datetime()), e8601dt16.)); 
  %let font='Courier New';
  %let size=8pt; 
  proc sql noprint;
    select distinct max(page) into :PAGES trimmed from &inds.;
    select distinct NAME into :COLS separated by " " from sashelp.VCOLUMN where LIBNAME="WORK" and upcase(MEMNAME)=upcase("&inds") and compress(upcase(NAME),,'d')="COL" order by input(compress(NAME,,'kd'),?best.);
    %let COLS=%left(%sysfunc(compbl(&COLS)));
    select distinct NAME into :ORDS separated by " " from sashelp.VCOLUMN where LIBNAME="WORK" and upcase(MEMNAME)=upcase("&inds") and compress(upcase(NAME),,'d')="ORD" order by input(compress(NAME,,'kd'),?best.);
    %let ORDS=%left(%sysfunc(compbl(&ORDS)));
    select distinct LABEL into :LBLS separated by "|" from sashelp.VCOLUMN where LIBNAME="WORK" and upcase(MEMNAME)=upcase("&inds") and compress(upcase(NAME),,'d')="COL" order by input(compress(NAME,,'kd'),?best.);
    %let LBLS=%left(&LBLS);
  quit;
  %put NOTE: &=pages;
  %put NOTE: &=cols;
  %put NOTE: &=ords;
  %if %length(&colwidth)=0 %then %do;
    %put NOTE: Derive column width:;
    %let trtcolw=%left(%eval(100/(%sysfunc(countw(&cols.))-1)))%str(%%);
    %let colwidth=25%str(%%); * First column *;
    %do i=2 %to %sysfunc(countw(&cols.));
      %let colwidth=%left(&colwidth) &trtcolw;
    %end;
    %put NOTE: &=colwidth;
  %end;
  title1 color=black h=&size. j=l "ZYUS-Z-TRI-10002A";
  title2 color=black h=&size. j=l "DSMB &dttm.";
  title3 color=black h=&size. j=c "&ttl.";
  title4 color=black h=&size. j=c "&pop.";
  footnote1 color=black h=&size. j=c "&esc.{style [borderbottomwidth=1pt just=center] }";
  footnote2 color=black h=&size. j=l "Source: &src.; Program name: &pgmname; Program run date: &dttm. Page \chpgn &esc.wof &pages.";

  proc report data=&inds. nowd headskip headline split="&split" missing wrap spacing=4 style(header)=[size=&size.] style(column)=[size=&size.] style(lines)=[size=&size.] style(summary)=[size=&size.];
    by page; 
    column PAGE SEC &ords. &cols.;

    define PAGE /  noprint order;
    define SEC  /  noprint group;
    %do _i=1 %to %sysfunc(countw(&ords.)); define %scan(&ords., &_i.) / noprint group; %end;
    %do _i=1 %to %sysfunc(countw(&cols.));
      define %scan(&cols.,&_i.) / "%scan(&lbls, &_i)" style(column)=[width=%scan(&colwidth.,&_i.) just=l asis=on] style(header)=[just=l asis=on borderbottomcolor=black borderbottomwidth=1];
    %end;

    compute before PAGE / style=[just=l]; line " "; endcomp; 
    compute after  SEC  / style=[just=l]; line " "; endcomp;
    compute after  PAGE / style=[just=l]; line " "; endcomp; 
  run;

  ods rtf close;
  ods listing;
%mend reptbl;

/*** END OF THE PROGRAM ***/
